<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="19.995" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2023-11-14T13:52:08" tests="0" file="cypress\e2e\API\secondTest.spec.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Test log out" timestamp="2023-11-14T13:52:08" tests="1" time="19.990" failures="1">
    <testcase name="Test log out verify use can log out successfully" time="6.107" classname="verify use can log out successfully">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (webpack://angular-realworld/./cypress/e2e/API/secondTest.spec.js:12:30)]]></failure>
    </testcase>
  </testsuite>
</testsuites>